FROM node:alpine as builder
LABEL maintainer="Julio Cesar <julio@blackdevs.com.br>"

WORKDIR /app
COPY frontend/package.json .
RUN npm install
COPY ./frontend .
RUN npm run build
# /app/build will be the directory of files

FROM nginx

RUN apt-get update && apt-get install -y curl git

COPY --from=builder /app/dist /usr/share/nginx/html
RUN sleep 5

# Build this image
# docker image build -f Dockerfile-front -t app-search-cities .

# Run this image
# docker container run --name app-search-cities -p 8090:80 app-search-cities
# docker container run -it --name app-search-cities -p 8090:80 app-search-cities bash
