FROM node:alpine
LABEL maintainer="Julio Cesar <julio@blackdevs.com.br>"

WORKDIR /app
COPY frontend/package.json .
RUN npm install
COPY ./frontend .

CMD ["npm", "run", "start"]

# Build this image
# docker image build -f Dockerfile-front-dev -t app-search-cities-dev .

# Run this image
# docker container run --name app-search-cities-dev -p 8080:8080 app-search-cities-dev
# docker container run -it --name app-search-cities-dev -p 8080:8080 app-search-cities-dev bash
